fix: keep using TLS 1.2
pivotal/credhub-release pull request #107
Opened 2023-01-19 00:31 UTC by swalchemist

Cherry-pick of a change that was previously reverted. The change was in support of a java 8 patch bump. We're now on Java 11 and need this change. This is expected to fix an error in four different deploy tasks in various acceptance test jobs that use Postgres:
```
Task 211465 | 14:42:51 | L starting jobs: credhub/d43321d0-b68d-4a52-8be7-cf3e9f109904 (0) (canary) (00:03:29)
                       L Error: 'credhub/d43321d0-b68d-4a52-8be7-cf3e9f109904 (0)' is not running after update. Review logs for failed jobs: credhub
```

This was associated with this error in the CredHub log:
```
2023-01-13T21:38:03.666Z [main] .... DEBUG --- HikariPool: HikariPool-1 - Cannot acquire connection from data source
org.postgresql.util.PSQLException: SSL error: Received fatal alert: handshake_failure
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:43) ~[postgresql-42.5.1.jar!/:42.5.1]
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584) ~[postgresql-42.5.1.jar!/:42.5.1]
...
```
Tested locally in the CredHub repo like so, where the last -D option fixed the error on startup:
```
./scripts/start_server.sh -Dspring.profiles.active=dev,dev-postgres -Djdk.tls.client.protocols=TLSv1.2
```
Original commit message:

- The bumped java version (provided by Bellsoft) contains this change: "8245263	Enable TLSv1.3 by default on JDK 8u for Client roles" (https://bell-sw.com/pages/liberica-release-notes-8u352/)
- However, many of our CI jobs failed likley because the latest postgres-release (contains postgres 11) does not accept TLS 1.3.
- So this commit reverts back to using TLS 1.2 (the prior default) to fix CI.
- We will bump credhub to use TLS 1.3 in the future, when needed.

[#183799645]
[#184142402]

2023-01-19 02:12 UTC, hsinn0 approved these changes

2023-01-20 06:29 UTC, peterhaochen47 approved these changes
Let's merge this PR such that we can start reproducing issue https://github.com/pivotal/credhub-release/issues/74

2023-01-20 18:24 UTC, bruce-ricard requested changes
As we discussed in person with @swalchemist and @Tallicia, I don't think we should pull this change into our main branch. We want credhub to make TLS connections using TLS 1.3, NOT 1.2.

2023-01-20 18:55 UTC, swalchemist commented
Update: we're now trying allow the database connections to work with TLS 1.3 by adding a named group.

2023-01-20 18:55 UTC, bruce-ricard approved these changes
LGTM, let's try it

2023-01-20 18:55 UTC, Tallicia commented
The mob agrees, we are shipping it.

2023-01-20 18:55 UTC, merged