PR for setting the timeout on the credhub webserver
pivotal/credhub-release pull request #57
Opened 2021-04-01 10:38 UTC by manucloud9

2021-06-11 08:34 UTC, bruce-ricard requested changes
Hi, thank you for your PR.

As the first commit apparently mistakingly sets the default timeout to 400 seconds, would you please mind squashing the 2 commits together?

Have you tested your changes locally? When you start a CredHub server with the updated manifest, does it wait the correct amount of time?

2021-06-16 10:11 UTC, benjaminguttmann-avtq commented
@bruce-ricard squashed the commits as requested

2021-06-17 08:49 UTC, bruce-ricard approved these changes
Thank you. LGTM.

2021-06-22 22:31 UTC, peterhaochen47 approved these changes
LGTM

2021-07-21 12:36 UTC, benjaminguttmann-avtq commented
@bruce-ricard @peterhaochen47 
is something that I am not aware of blocking this one from getting merged? Thanks.

2021-07-21 17:02 UTC, merged

2021-07-21 17:03 UTC, bruce-ricard commented
Sorry Benjamin, I forgot to merge.